<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateNewsTagTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('news_tag', function (Blueprint $table) {
            $table->unsignedInteger('news_id');
            $table->unsignedInteger('tag_id');
            $table->timestamps();

            $table->index('news_id', 'news_tag_news_id_index');
            $table->index('tag_id', 'news_tag_tag_id_index');

            $table->foreign('news_id', 'news_tag_news_id_foreign')->references('id')->on('news')->onDelete('CASCADE
')->onUpdate('RESTRICT');
            $table->foreign('tag_id', 'news_tag_tag_id_foreign')->references('id')->on('tags')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('news_tag');
    }
}
