<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProductModelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_models', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('product_id');
            $table->string('title', 255);
            $table->text('description');
            $table->string('image', 255)->nullable();
            $table->integer('sort');
            $table->tinyInteger('pub')->nullable()->default(1);
            $table->integer('created_by');
            $table->unsignedInteger('finishing_id')->nullable();
            $table->string('code', 100);
            $table->integer('color_id')->nullable();
            $table->string('feature', 255)->nullable();
            $table->string('doc', 255);
            $table->timestamps();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_models');
    }
}
