<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateArticlesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('articles', function (Blueprint $table) {
            $table->increments('id');
            $table->string('domain', 255);
            $table->integer('id_parent');
            $table->integer('id_template');
            $table->string('menu_title', 255)->nullable();
            $table->string('title', 255)->nullable();
            $table->string('subtitle', 255)->nullable();
            $table->string('intro', 255)->nullable();
            $table->string('abstract', 255)->nullable();
            $table->text('description');
            $table->string('slug', 255)->nullable();
            $table->string('doc', 255);
            $table->string('image', 255);
            $table->string('banner', 255);
            $table->string('link', 255);
            $table->integer('sort');
            $table->tinyInteger('pub')->nullable()->default(1);
            $table->tinyInteger('top_menu')->nullable()->default(1);
            $table->integer('template_id')->nullable();
            $table->integer('created_by');
            $table->timestamps();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('articles');
    }
}
