<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateArticleTranslationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('article_translations', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('article_id');
            $table->string('locale', 255);
            $table->string('menu_title', 255)->nullable();
            $table->string('title', 255);
            $table->string('subtitle', 255)->nullable();
            $table->string('intro', 255)->nullable();
            $table->text('description');
            $table->text('abstract')->nullable();
            $table->string('seo_title', 255)->nullable();
            $table->string('seo_description', 255)->nullable();
            $table->string('seo_keywords', 255)->nullable();
            $table->string('seo_no_index', 255)->nullable();
            $table->integer('created_by');
            $table->integer('update_by');
            $table->timestamps();

            $table->unique(['article_id', 'locale'], 'article_translations_article_id_locale_unique');
            $table->index('locale', 'article_translations_locale_index');

            $table->foreign('article_id', 'article_translations_article_id_foreign')->references('id')->on('articles')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('article_translations');
    }
}
