<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateContactsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('contacts', function (Blueprint $table) {
            $table->increments('id');
            $table->string('request_product_id', 255)->nullable();
            $table->string('subject', 255);
            $table->text('message');
            $table->string('name', 255)->nullable();
            $table->string('company', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('phone', 255);
            $table->tinyInteger('status')->nullable();
            $table->integer('created_by');
            $table->timestamps();
            $table->softDeletes();
            $table->string('surname', 255);
            $table->string('lang', 5);
            $table->text('replay')->nullable();
            $table->string('fax', 100)->nullable();
            $table->string('zip_code', 10)->nullable();
            $table->integer('user_type_id')->nullable();
            $table->integer('request_type_id')->nullable();
            $table->integer('country_id')->nullable();
            $table->string('country', 100)->nullable();
            $table->string('city', 255)->nullable();
            $table->string('address', 255)->nullable();
            $table->string('province', 200)->nullable();
            $table->tinyInteger('newsletter')->nullable();
            $table->string('product', 255)->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('contacts');
    }
}
